manager/manager/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("characters/", include("players_characters.urls")),
    path("world/", include("world.urls")),
]

manager/players_characters/urls.py
from django.urls import path

from . import views

app_name = "characters"
urlpatterns = [
    path("", views.PlayersCharactersListView.as_view(), name="players-characters-list"),
    path(
        "<int:pk>",
        views.PlayersCharactersDetails.as_view(),
        name="players-characters-details",
    ),
    path(
        "create",
        views.PlayersCharactersCreateView.as_view(),
        name="players-characters-creation",
    ),
    path(
        "update/<int:pk>",
        views.PlayersCharactersUpdateView.as_view(),
        name="players-characters-update",
    ),
    path(
        "delete/<int:pk>",
        views.PlayersCharactersDeleteView.as_view(),
        name="delete-characters",
    ),
]

manager/world/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.RegionsListView.as_view(), name="regions-list"),
    path(
        "create-region",
        views.RegionsCreateView.as_view(),
        name="regions-creation",
    ),
]

manager/account/models.py
from django.db import models

# Create your models here.

manager/players_characters/models.py
from django.db import models


class PlayersCharacters(models.Model):
    name = models.CharField(verbose_name="Nom du personnage", max_length=255)
    player = models.CharField(
        verbose_name="Nom du Joueur", max_length=255, null=True, blank=True
    )
    character_sheet_url = models.CharField(
        verbose_name="Url fiche de personnage", max_length=1080, null=True, blank=True
    )
    # character_sheet_file = models.FileField(verbose_name="Importer une fiche")

    def __str__(self) -> str:
        return self.name

    def __repr__(self):
        return self.name

manager/world/models.py
from django.db import models


class Regions(models.Model):
    name = models.CharField(max_length=240, verbose_name="Nom de la région")
    visited = models.BooleanField(default=False, verbose_name="Déjà visitée")
    religion = models.CharField(
        max_length=240, null=True, blank=True, verbose_name="Religion principale"
    )
    politic = models.CharField(
        max_length=240, null=True, blank=True, verbose_name="Sytème politique"
    )
    chief = models.CharField(
        max_length=240, null=True, blank=True, verbose_name="Chef connu"
    )
    region_maps_url = models.CharField(
        max_length=240, null=True, blank=True, verbose_name="Lien vers la carte"
    )
    description = models.TextField(null=True, blank=True, verbose_name="Description")
    history_in_campaign = models.TextField(
        null=True, blank=True, verbose_name="Activité importante lié à la campagne"
    )

manager/players_characters/views.py
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from players_characters.models import PlayersCharacters


class PlayersCharactersListView(ListView):
    model = PlayersCharacters
    paginate_by = 100
    template_name = "players_characters/list.html"


class PlayersCharactersCreateView(CreateView):
    model = PlayersCharacters
    fields = ["name", "player", "character_sheet_url"]
    template_name = "players_characters/creation.html"
    success_url = reverse_lazy("characters:players-characters-list")


class PlayersCharactersUpdateView(UpdateView):
    model = PlayersCharacters
    fields = ["name", "player", "character_sheet_url"]
    template_name = "players_characters/update.html"
    success_url = reverse_lazy("characters:players-characters-list")


class PlayersCharactersDetails(DetailView):
    model = PlayersCharacters


class PlayersCharactersDeleteView(DeleteView):
    model = PlayersCharacters
    success_url = reverse_lazy("characters:players-characters-list")

manager/world/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

from world.models import Regions


class RegionsListView(ListView):
    model = Regions
    paginate_by = 20
    template_name = "regions/list.html"


class RegionsCreateView(CreateView):
    model = Regions
    fields = [
        "name",
        "visited",
        "religion",
        "politic",
        "chief",
        "region_maps_url",
        "description",
        "history_in_campaign",
    ]
    template_name = "regions/creation.html"
    success_url = reverse_lazy("regions-list")


class RegionsUpdateView(UpdateView):
    model = Regions
    fields = [
        "name",
        "visited",
        "religion",
        "politic",
        "chief",
        "region_maps_url",
        "description",
        "history_in_campaign",
    ]
    template_name = "regions/update.html"
    success_url = reverse_lazy("regions-list")

manager/templates/players_characters/list.html
<h1>Personnages</h1>
<ul>
{% for character in object_list %}
    <li>{{ character.pk }} <a href="{% url 'characters:players-characters-details' character.pk %}"> {{ character.name }}</a></li>
    {% comment %} <li>{{ character.pk }} <a href="/characters/{{character.pk}}"> {{ character.name }}</a></li> {% endcomment %}
{% empty %}
    <li>Pas encore de personnages</li>
{% endfor %}
<a href="{% url 'characters:players-characters-creation' %}"> Create Character </a>
</ul>

manager/templates/players_characters/playerscharacters_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>

manager/templates/players_characters/playerscharacters_detail.html
<p>{{ object.name }}</p>
<p>{{ object.player }}</p>
<p>{{ object.character_sheet_url }}</p>
<a href={% url 'characters:delete-characters' object.pk %}> Delete </a>

manager/templates/regions/creation.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

manager/templates/regions/list.html
<h1>Régions</h1>
<ul>
{% for region in object_list %}
    <li>{{ region.name }}</li>
{% empty %}
    <li>Pas encore de régions</li>
{% endfor %}
<a href="{% url 'regions-creation' %}"> Créer une nouvelle région </a>
</ul>

manager/templates/regions/update.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>